import type { Property } from './types';

export const ALL_PROPERTIES: Property[] = [
  {
    id: '1',
    image: 'https://placehold.co/600x400.png',
    price: 25000000,
    address: '123 MG Road',
    city: 'Bangalore',
    state: 'KA',
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    propertyType: 'Apartment',
    description: 'A spacious and modern apartment in the heart of Bangalore.',
  },
  {
    id: '2',
    image: 'https://placehold.co/600x400.png',
    price: 45000,
    address: '456 Juhu Beach Rd',
    city: 'Mumbai',
    state: 'MH',
    bedrooms: 2,
    bathrooms: 1,
    area: 950,
    propertyType: 'Apartment',
    description: 'A beautiful sea-facing apartment in a prime location in Mumbai.',
  },
  {
    id: '3',
    image: 'https://placehold.co/600x400.png',
    price: 18000000,
    address: '789 Connaught Place',
    city: 'Delhi',
    state: 'DL',
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    propertyType: 'Condo',
    description: 'A luxurious condo in a prestigious area of Delhi with all amenities.',
  },
  {
    id: '4',
    image: 'https://placehold.co/600x400.png',
    price: 60000000,
    address: '101 Boat Club Road',
    city: 'Chennai',
    state: 'TN',
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    propertyType: 'House',
    description: 'An elegant and spacious house in a posh locality of Chennai.',
  },
  {
    id: '5',
    image: 'https://placehold.co/600x400.png',
    price: 30000,
    address: '222 Park Street',
    city: 'Kolkata',
    state: 'WB',
    bedrooms: 1,
    bathrooms: 1,
    area: 700,
    propertyType: 'Apartment',
    description: 'A well-maintained apartment in the bustling Park Street area of Kolkata.',
  },
  {
    id: '6',
    image: 'https://placehold.co/600x400.png',
    price: 35000000,
    address: '333 Jubilee Hills',
    city: 'Hyderabad',
    state: 'TS',
    bedrooms: 4,
    bathrooms: 2.5,
    area: 2200,
    propertyType: 'House',
    description: 'A beautiful house in the upscale Jubilee Hills area of Hyderabad.',
  },
];
