import type { Property } from './types';

export const ALL_PROPERTIES: Property[] = [
  {
    id: '1',
    image: 'https://placehold.co/600x400.png',
    price: 450000,
    address: '123 Maple St',
    city: 'Springfield',
    state: 'IL',
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    propertyType: 'House',
    description: 'A beautiful family home in a quiet suburban neighborhood.',
  },
  {
    id: '2',
    image: 'https://placehold.co/600x400.png',
    price: 2200,
    address: '456 Oak Ave, Apt 12',
    city: 'Metropolis',
    state: 'NY',
    bedrooms: 2,
    bathrooms: 1,
    area: 950,
    propertyType: 'Apartment',
    description: 'Modern apartment in the heart of the city with great views.',
  },
  {
    id: '3',
    image: 'https://placehold.co/600x400.png',
    price: 320000,
    address: '789 Pine Ln',
    city: 'Greenville',
    state: 'SC',
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    propertyType: 'Condo',
    description: 'Cozy condo with access to community pool and gym.',
  },
  {
    id: '4',
    image: 'https://placehold.co/600x400.png',
    price: 750000,
    address: '101 Ocean Blvd',
    city: 'Malibu',
    state: 'CA',
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    propertyType: 'House',
    description: 'Stunning beachfront property with panoramic ocean views.',
  },
  {
    id: '5',
    image: 'https://placehold.co/600x400.png',
    price: 1800,
    address: '222 Downtown St, Unit 301',
    city: 'Austin',
    state: 'TX',
    bedrooms: 1,
    bathrooms: 1,
    area: 700,
    propertyType: 'Apartment',
    description: 'Chic downtown apartment perfect for a young professional.',
  },
  {
    id: '6',
    image: 'https://placehold.co/600x400.png',
    price: 550000,
    address: '333 Suburbia Ct',
    city: 'Springfield',
    state: 'IL',
    bedrooms: 4,
    bathrooms: 2.5,
    area: 2200,
    propertyType: 'House',
    description: 'Spacious home with a large backyard, ideal for families.',
  },
];
